defmodule Demo.Repo.Migrations.InitialSetup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :hashed_password, :text
      add :name, :text
      add :status, :text, default: "active"
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    create table(:linked_accounts, primary_key: false) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :status, :text, default: "active"
      add :session_token, :uuid, null: false
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :linked_user_id,
          references(:users,
            column: :id,
            name: "linked_accounts_linked_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :primary_user_id,
          references(:users,
            column: :id,
            name: "linked_accounts_primary_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:linked_accounts, [:primary_user_id, :linked_user_id, :session_token],
             name: "linked_accounts_unique_linked_user_session_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :linked_accounts,
                     [:primary_user_id, :linked_user_id, :session_token],
                     name: "linked_accounts_unique_linked_user_session_index"
                   )

    drop constraint(:linked_accounts, "linked_accounts_linked_user_id_fkey")

    drop constraint(:linked_accounts, "linked_accounts_primary_user_id_fkey")

    drop table(:linked_accounts)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end
