defmodule Demo.Repo.Migrations.MakeNameRequired do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Backfill existing rows that have null names with the email local part
    execute "UPDATE users SET name = split_part(email, '@', 1) WHERE name IS NULL"

    alter table(:users) do
      modify :name, :text, null: false
    end
  end

  def down do
    alter table(:users) do
      modify :name, :text, null: true
    end
  end
end
